name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3

      - name: Install QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system-x86

      - name: Setup Rust Nightly Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: x86_64-unknown-none

      - name: Add rust-src and llvm-tools-preview Components
        run: |
          rustup component add rust-src --toolchain nightly
          rustup component add llvm-tools-preview --toolchain nightly

      - name: Install bootimage
        run: cargo install bootimage

      - name: Build OS
        run: cargo build
        
      - name: Run Unit Tests
        run: cargo test
